message(STATUS "Conan: Using CMakeDeps conandeps_legacy.cmake aggregator via include()")
message(STATUS "Conan: It is recommended to use explicit find_package() per dependency instead")

find_package(pegtl)
find_package(Catch2)
find_package(restbed)
find_package(spdlog)
find_package(nlohmann_json)
find_package(fmt)
find_package(httplib)
find_package(nextsilicon-cpp-subprocess)
find_package(jwt-cpp)
find_package(OpenSSL)
find_package(SQLite3)

set(CONANDEPS_LEGACY  taocpp::pegtl  Catch2::Catch2WithMain  restbed::restbed  spdlog::spdlog  nlohmann_json::nlohmann_json  fmt::fmt  httplib::httplib  nextsilicon-cpp-subprocess::nextsilicon-cpp-subprocess  jwt-cpp::jwt-cpp  openssl::openssl  SQLite::SQLite3 )