// SPDX-License-Identifier: MPL-2.0
/**
 * @file isched_UiAssetRegistry.hpp
 * @brief In-memory registry of compiled Angular admin UI assets.
 *
 * Populated at program start from the embedded byte arrays generated by
 * tools/embed_ui_assets.py into isched_ui_assets.hpp.
 *
 * Thread-safe after construction (read-only singleton).
 */
#pragma once

#include <cstdint>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <unordered_map>

namespace isched::v0_0_1::backend {

/// A single UI asset entry returned by UiAssetRegistry::find().
struct UiAssetView {
    std::span<const uint8_t> data;       ///< Raw file bytes
    std::string_view         mime_type;  ///< MIME type with optional charset
    std::string_view         etag;       ///< Pre-computed ETag (16-char hex SHA-256 prefix)
};

/**
 * @brief Read-only singleton that maps URL paths to compiled Angular assets.
 *
 * Call @c instance() to obtain a reference. The registry is built once from
 * the generated @c ISCHED_UI_ASSET_MAP array at first access and is
 * subsequently immutable — no locking required for reads.
 *
 * The URL paths stored here are relative to the @c /isched prefix and always
 * begin with @c '/'.  E.g. @c "/index.html", @c "/main-XXXX.js".
 */
class UiAssetRegistry {
public:
    /// Return the singleton instance. Thread-safe (static local initialization).
    static const UiAssetRegistry& instance();

    /**
     * @brief Look up an asset by URL path.
     * @param url_path  Path relative to the @c /isched prefix (must start with @c '/').
     * @return          Asset entry if found; @c std::nullopt otherwise.
     */
    [[nodiscard]] std::optional<UiAssetView> find(std::string_view url_path) const;

    /**
     * @brief True when @c /index.html is present in the registry.
     *
     * Used as a sentinel: if false the build artefacts are missing and the
     * server should return HTTP 503 rather than serving stale or empty content.
     */
    [[nodiscard]] bool has_index_html() const noexcept;

    /// Number of assets in the registry.
    [[nodiscard]] std::size_t size() const noexcept;

private:
    UiAssetRegistry();

    std::unordered_map<std::string, UiAssetView> m_assets;
    bool                                          m_has_index_html{false};
};

} // namespace isched::v0_0_1::backend
